"$schema" = 'https://starship.rs/config-schema.json'

[aws]
disabled  = true

[cmd_duration]
disabled = true

[directory]
truncation_length = 0

[git_metrics]
disabled = false

[os]
disabled = false
style = "bold blue"

[os.symbols]
Fedora = "  "

[package]
disabled = true

[shell]
disabled = false
fish_indicator = '  '
bash_indicator = '  '
zsh_indicator = ' %'
style = 'cyan bold'
